settings:
  title: '狀態列表'
  url: 'https://status.youzi.cloudns.ch' # used for Slack messages
  logo: status.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '所有系統運行正常'
  notAllmonitorsOperational: '並非所有系統運作中'
  monitorLabelOperational: '運作中'
  monitorLabelNotOperational: '未運作'
  monitorLabelNoData: '沒有資料'
  dayInHistogramNoData: '沒有資料'
  dayInHistogramOperational: '運行穩定'
  dayInHistogramNotOperational: '事件' # xx incident(s) recorded

monitors:
  - id: www-youzi # unique identifier
    name: www.youzi.cloudns.ch
    description: '主要網站' # default=empty
    url: 'https://www.youzi.cloudns.ch/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: bot-youzi # unique identifier
    name: bot.youzi.cloudns.ch
    description: 'Discord機器人網站' # default=empty
    url: 'https://bot.youzi.cloudns.ch/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true


